### ISSUE TITLE
A tracker for APF.m 0.2.0

### ISSUE THREAD

**Issue by christian-cahig** [christian-cahig/Masterarbeit-APF#88]
- [x] Update `makeC` to adopt new naming scheme outlined in #87
- [x] Refactor `buildSnapshotData` to only synthesize snapshot data
- [x] Add `saveSnapshotData` for exporting snapshot data in APF.m or PyAPF format
- [x] Calculate for and save `W` in `saveSnapshotData` for PyAPF format
- [x] Update help texts to include new naming scheme
- [x] Rename `apfver` to `APFver`
- [x] Add `defaultAPFOptions`
- [x] Add `getLoadedBuses`
- [x] Bump version to 0.2.0
